### ISSUE TITLE
Use JMH for microbenchmarks

### ISSUE THREAD

**Issue by leozilla** [networknt/json-schema-validator-perftest#1]
The tests give a false sense of the performance of these libraries.

Please use http://openjdk.java.net/projects/code-tools/jmh/ or consider removing the tests altogether.

**Comment by stevehu** [comment]
Thanks for the recommendation and I will keep this issue open until it is implemented. I agree that these are not absolute numbers but relative numbers. And it is the same approach the other validator took.
