### ISSUE TITLE
Results are not reproducible

### ISSUE THREAD

**Issue by dreis2211** [networknt/json-schema-validator-perftest#6]
Hi,

the latest results posted from @stevehu are not reproducible. 

IDE
```
everit-org(1.14.1): 260 ms
networknt(1.0.69): 196 ms
```

First of all, are these manually averaged results? Or the end/total time posted by either test?

I get the following results for **networknt**:
```
Initial validation :20 ms
Iteration 0 (in 4 ms)
Iteration 20 (in 135 ms)
Iteration 40 (in 358 ms)
Iteration 60 (in 484 ms)
Iteration 80 (in 591 ms)
Iteration 100 (in 646 ms)
Iteration 120 (in 692 ms)
Iteration 140 (in 735 ms)
Iteration 160 (in 778 ms)
Iteration 180 (in 826 ms)
Iteration 200 (in 858 ms)
Iteration 220 (in 886 ms)
Iteration 240 (in 913 ms)
Iteration 260 (in 938 ms)
Iteration 280 (in 962 ms)
Iteration 300 (in 987 ms)
Iteration 320 (in 1004 ms)
Iteration 340 (in 1021 ms)
Iteration 360 (in 1043 ms)
Iteration 380 (in 1077 ms)
Iteration 400 (in 1107 ms)
Iteration 420 (in 1136 ms)
Iteration 440 (in 1158 ms)
Iteration 460 (in 1177 ms)
Iteration 480 (in 1196 ms)
END -- time in ms: 1213
```

And this for **Everit**:
```
Now test overit...
Iteration 0 (in 29ms)
Iteration 20 (in 105ms)
Iteration 40 (in 135ms)
Iteration 60 (in 162ms)
Iteration 80 (in 200ms)
Iteration 100 (in 262ms)
Iteration 120 (in 305ms)
Iteration 140 (in 345ms)
Iteration 160 (in 375ms)
Iteration 180 (in 407ms)
Iteration 200 (in 440ms)
Iteration 220 (in 475ms)
Iteration 240 (in 508ms)
Iteration 260 (in 540ms)
Iteration 280 (in 567ms)
Iteration 300 (in 596ms)
Iteration 320 (in 622ms)
Iteration 340 (in 644ms)
Iteration 360 (in 666ms)
Iteration 380 (in 692ms)
Iteration 400 (in 725ms)
Iteration 420 (in 755ms)
Iteration 440 (in 788ms)
Iteration 460 (in 813ms)
Iteration 480 (in 834ms)
total time: 850 ms
```

**Test machine:** 
MacBook Pro (2019)
CPU: 2,3 GHz 8-Core Intel Core i9
Memory: 32 GB 2400 MHz DDR4
Java 11.0.11

I would appreciate if the results would include the test machine specs - like I posted mine - and would describe what they actually show (total time; average time). Running the code doesn't output what is documented in the README.

Additionally, it should be really considered to move things to JMH as the results are way too volatile. I could offer my support here.

Cheers,
Christoph

**Comment by stevehu** [comment]
My desktop is Ryzen 5900 12-Core with 64GB memory. I've learned that IntelliJ IDEA will cover some code to C to speed up the execution. We can ignore the result from the IDEs. Thanks a lot for the JMH implementation and it is consistent regardless of which computer to run it. Based on the benchmarks, we are sure that we have some performance issues with the latest features.

**Comment by stevehu** [comment]
@dreis2211 There is another benchmark comparison from a third party. https://www.creekservice.org/json-schema-validation-comparison/performance#json-schema-test-suite-benchmark
